# Generated by Django 4.2.5 on 2023-10-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aboutResume", models.CharField(max_length=500)),
                ("aboutComplete", models.TextField()),
                (
                    "aboutImages",
                    models.ImageField(upload_to="portfolioImages/about_images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blogCategories", models.CharField(max_length=500)),
                ("blogFile", models.FileField(upload_to="portfolioImages/blog_files/")),
                ("blogFileContent", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectResume", models.CharField(max_length=500)),
                ("projectComplete", models.TextField()),
                (
                    "projectImages",
                    models.ImageField(upload_to="portfolioImages/project_images/"),
                ),
                ("projectWebsiteResume", models.TextField()),
                (
                    "projectWebsiteImages",
                    models.ImageField(
                        upload_to="portfolioImages/project_website_images/"
                    ),
                ),
                ("projectWebsiteUrl", models.URLField()),
                ("projectWebsiteTools", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skillsResume", models.CharField(max_length=500)),
                ("skillComplete", models.TextField()),
                ("programingLanguageResume", models.TextField()),
                (
                    "programingLanguageImages",
                    models.ImageField(
                        upload_to="portfolioImages/programming_language_images/"
                    ),
                ),
                ("userInterfaceResume", models.TextField()),
                (
                    "userInterfaceImages",
                    models.ImageField(
                        upload_to="portfolioImages/user_interface_images/"
                    ),
                ),
                ("developmentToolsResume", models.TextField()),
                (
                    "developmentToolsImages",
                    models.ImageField(
                        upload_to="portfolioImages/development_tools_images/"
                    ),
                ),
                ("databasesResume", models.TextField()),
                (
                    "databasesImages",
                    models.ImageField(upload_to="portfolioImages/databases_images/"),
                ),
                ("dataProcessingResume", models.TextField()),
                (
                    "dataProcessingImages",
                    models.ImageField(
                        upload_to="portfolioImages/data_processing_images/"
                    ),
                ),
                ("operatingSystemsResume", models.TextField()),
                (
                    "operatingSystemsImages",
                    models.ImageField(
                        upload_to="portfolioImages/operating_systems_images/"
                    ),
                ),
            ],
        ),
    ]
