# Generated by Django 4.2.5 on 2023-10-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="aboutImages",
            field=models.ImageField(
                blank=True, null=True, upload_to="portfolioImages/about_images/"
            ),
        ),
    ]
