# Generated by Django 4.2.5 on 2023-10-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_about_aboutimages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="aboutImages",
            field=models.ImageField(blank=True, null=True, upload_to="about_images/"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="blogFile",
            field=models.FileField(upload_to="blog_files/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="projectImages",
            field=models.ImageField(upload_to="project_images/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="projectWebsiteImages",
            field=models.ImageField(upload_to="project_website_images/"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="dataProcessingImages",
            field=models.ImageField(upload_to="data_processing_images/"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="databasesImages",
            field=models.ImageField(upload_to="databases_images/"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="developmentToolsImages",
            field=models.ImageField(upload_to="development_tools_images/"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="operatingSystemsImages",
            field=models.ImageField(upload_to="operating_systems_images/"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="programingLanguageImages",
            field=models.ImageField(upload_to="programming_language_images/"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="userInterfaceImages",
            field=models.ImageField(upload_to="user_interface_images/"),
        ),
    ]
