# Generated by Django 4.2.5 on 2023-10-25 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_about_aboutimages_alter_blog_blogfile_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="projectImages",
            new_name="projectImage",
        ),
        migrations.RemoveField(
            model_name="project",
            name="projectWebsiteImages",
        ),
        migrations.RemoveField(
            model_name="project",
            name="projectWebsiteTools",
        ),
        migrations.CreateModel(
            name="ProjectImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "projectWebsiteImages",
                    models.ImageField(
                        blank="True", upload_to="project_website_images/"
                    ),
                ),
                (
                    "projectWebsiteTools",
                    models.ImageField(
                        blank="True", upload_to="project_website_images_tools/"
                    ),
                ),
                (
                    "Project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.project"
                    ),
                ),
            ],
        ),
    ]
