# Generated by Django 4.2.5 on 2023-10-26 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_alter_blogcategory_blogresume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimages",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="tasks.project",
            ),
        ),
        migrations.AlterField(
            model_name="skillsimages",
            name="skills",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="tasks.skill",
            ),
        ),
    ]
