# Generated by Django 4.2.5 on 2023-10-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0007_alter_projectimages_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="projectName",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
