# Generated by Django 4.2.5 on 2023-10-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0008_project_projectname"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contactResume", models.CharField(max_length=500)),
                ("contactComplete", models.TextField()),
                ("youtubeUrl", models.URLField()),
                ("instagramUrl", models.URLField()),
                ("githubUrl", models.URLField()),
            ],
        ),
    ]
