# Generated by Django 4.2.5 on 2023-10-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0009_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="linkedinUrl",
            field=models.URLField(blank=True),
        ),
    ]
