# Generated by Django 4.2.5 on 2023-10-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0010_contact_linkedinurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="linkedinUrl",
            field=models.URLField(),
        ),
    ]
