# Generated by Django 4.2.5 on 2023-10-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0011_alter_contact_linkedinurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="githubImage",
            field=models.ImageField(blank=True, upload_to="contact_images/"),
        ),
        migrations.AddField(
            model_name="contact",
            name="instagramImage",
            field=models.ImageField(blank=True, upload_to="contact_images/"),
        ),
        migrations.AddField(
            model_name="contact",
            name="linkedinImage",
            field=models.ImageField(blank=True, upload_to="contact_images/"),
        ),
        migrations.AddField(
            model_name="contact",
            name="youtubeImage",
            field=models.ImageField(blank=True, upload_to="contact_images/"),
        ),
    ]
