# Generated by Django 4.2.5 on 2023-10-31 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0012_contact_githubimage_contact_instagramimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimages",
            name="projectWebsiteImages",
            field=models.FileField(blank=True, upload_to="project_website_images/"),
        ),
        migrations.AlterField(
            model_name="projectimages",
            name="projectWebsiteTools",
            field=models.FileField(
                blank=True, upload_to="project_website_images_tools/"
            ),
        ),
    ]
