# Generated by Django 4.2.5 on 2023-11-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0013_alter_projectimages_projectwebsiteimages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillsimages",
            name="dataProcessingImages",
            field=models.FileField(blank=True, upload_to="data_processing_images/"),
        ),
        migrations.AlterField(
            model_name="skillsimages",
            name="databasesImages",
            field=models.FileField(blank=True, upload_to="databases_images/"),
        ),
        migrations.AlterField(
            model_name="skillsimages",
            name="developmentToolsImages",
            field=models.FileField(blank=True, upload_to="development_tools_images/"),
        ),
        migrations.AlterField(
            model_name="skillsimages",
            name="operatingSystemsImages",
            field=models.FileField(blank=True, upload_to="operating_systems_images/"),
        ),
        migrations.AlterField(
            model_name="skillsimages",
            name="programingLanguageImages",
            field=models.FileField(
                blank=True, upload_to="programming_language_images/"
            ),
        ),
        migrations.AlterField(
            model_name="skillsimages",
            name="userInterfaceImages",
            field=models.FileField(blank=True, upload_to="user_interface_images/"),
        ),
    ]
