# Generated by Django 4.2.5 on 2023-11-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0014_alter_skillsimages_dataprocessingimages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="aboutResume",
            field=models.TextField(),
        ),
    ]
